spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1020609323835-mph2ouc0i1ff6ij1a456bggach8gjo2s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
              - email
              - profile
          kakao:
            client-id: b8f3486575b72565c36b0c665b266365
            client-secret: 5GPcb4Iissy3tdmWA5I3pJ8TwXAgTsKB
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - account_email
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/testcase
    username: sa
  h2:
    console:
      enabled: true
jwt:
  secret_key: 0852712ba4290435a5c95068466f7cfb579762fe49b6879bb364055ba9ba90cb
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    spring.jpa.open-in-view: false
    org.hibernate.SQL: info #debug
    org.hibernate.type.descriptor.sql: info #trace